name: 'Terraform Plan'
on:
  - push
  - pull_request

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1.1.0
        with:
          terraform_version: 0.12.0
      - name: 'Terraform Init'
        run: terraform init
        working-directory: terraform/dns
      - name: 'Terraform Format'
        run: terraform fmt -check
        working-directory: terraform/dns
      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: terraform/dns
        env:
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
